-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 11:45:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NewProject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `NewProject` ;

-- -----------------------------------------------------
-- Schema NewProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NewProject` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `NewProject` ;

-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comment` (
  `idcomment` INT NOT NULL,
  `idpost` INT NOT NULL,
  `idreaction` INT NOT NULL,
  `reaction_number` INT NULL,
  `post_idpost` INT NOT NULL,
  `reaction_idreaction` INT NOT NULL,
  PRIMARY KEY (`idcomment`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `post` (
  `idpost` INT NOT NULL,
  `idreaction` INT NOT NULL,
  `reaction_number` INT NULL,
  `reaction_idreaction` INT NOT NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `reaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `reaction` (
  `idreaction` INT NOT NULL,
  PRIMARY KEY (`idreaction`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `story` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `story` (
  `idstory` INT NOT NULL,
  `idreaction` INT NOT NULL,
  `reaction_number` INT NULL,
  `reaction_idreaction` INT NOT NULL,
  PRIMARY KEY (`idstory`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL,
  `firstname` VARCHAR(10) NOT NULL,
  `lastname` VARCHAR(10) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `birthday` DATETIME NULL,
  `userimage` BLOB NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_has_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_has_comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_has_comment` (
  `user_iduser` INT NOT NULL,
  `comment_idcomment` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `comment_idcomment`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_has_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_has_post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_has_post` (
  `user_iduser` INT NOT NULL,
  `post_idpost` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `post_idpost`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_has_story`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_has_story` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_has_story` (
  `user_iduser` INT NOT NULL,
  `story_idstory` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `story_idstory`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
